### PR TITLE
WIP: Output widget

### PR DESCRIPTION
**Pull request by sumitsahrawat**
- Add Output Widget to ihaskell-widgets
- Add support for sending `display_data` messages as custom messages.

@gibiansky Take a look at this. The `setOutput` function actually appends displays to the widget.

Implementing clearOutput will require some different mechanism. Sending a complete `clear_output` message doesn't work.

### CODE REVIEW

**Comment by gibiansky** [comment]
Hmm, I took a look at the code and it looks solid: seems like it should send a `display_data` for each change with `method: 'custom'`. This is what we want, right? 

If so, what does IPython do? How does their sequence of messages differ from this one?

**Comment by sumitsahrawat** [comment]
Our messages are identical to IPython for output. They also additionally have a clear_output function for their output widget.

I'm still a bit confused about how it works. Sending a `clear_output` message similar to display_data didn't work, and the JS indicates that only `display_data`, `stream` and `execute_reply` messages are accepted that way.

**Comment by gibiansky** [comment]
What was the error that made it append rather than replace?

**Comment by sumitsahrawat** [comment]
It was supposed to append. That was not the issue. The issue was that the `clear_output` didn't work.

**Comment by gibiansky** [comment]
Ah! That makes sense.

**Comment by sumitsahrawat** [comment]
The IPython implementation took messages as they were being sent, converted them to a json message, and then sent them.

The `clear_output` messages were filtered out, and handled separately. For all other messages, the message was passed to another handler.

That is why I thought that widgets didn't accept `clear_output` messages.

**Pull request merged**
